config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  scope path_names: { new: "novo", edit: "editar" } do
    # seus resources
  end

  #sidekiq
  mount Sidekiq::Web => '/sidekiq'

  resources :pedidos do 
    resources :pedido_produtos
  end
  resources :receitas
  resources :despesas
  resources :fornecedores
  resources :produtos do
    collection { post :import }
  end
  resources :clientes
  resources :xml_products do
    collection {post :import }
  end

  root to:'home#index'
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

 
  def index
    @produtos = Produto.all
  end

  
  def show
  end


  def new
    @produto = Produto.new
  end

 
  def edit
  end

  def import
    @import_excel = ImportProductExcel.new(params[:file])
    if @import_excel.import
       redirect_to produtos_url, notice: 'Arquivo Importado' 
    else
      redirect_to produtos_url, notice: 'Erro ao Importar '
    end
  end

 
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   
    def set_produto
      @produto = Produto.find(params[:id])
    end

   
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :quantidade, :vecimento, :preco_compra, :preco_venda)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @produto.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h4>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descricao, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :descricao, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantidade, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :quantidade, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :vecimento, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_field :vecimento, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :preco_compra, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :preco_compra, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :preco_venda, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :preco_venda, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @produto, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing produto</h1>
</div>

<%= render 'form' %>

app/views/produtos/index.html.erb
<div class="page-header">
  <%= link_to new_produto_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Produto
  <% end %>
  <h1>Listing produtos</h1>
</div>
<%= form_tag import_produtos_path, multipart: true do %>
      <%= file_field_tag :file %><br>
      <%= submit_tag "Importar Planilha", class: 'btn btn-primary' %>
<% end %>
<br>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th>Descricao</th>
            <th>Quantidade</th>
            <th>Vecimento</th>
            <th>Preco compra</th>
            <th>Preco venda</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @produtos) do |produto| %>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.quantidade %></td>
            <td><%= produto.vecimento %></td>
            <td><%= produto.preco_compra %></td>
            <td><%= produto.preco_venda %></td>
            <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/produtos/new.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New produto</h1>
</div>

<%= render 'form' %>

app/views/produtos/show.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_produto_path(@produto), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show produto</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @produto.nome %></dd>

  <dt>Descricao:</dt>
  <dd><%= @produto.descricao %></dd>

  <dt>Quantidade:</dt>
  <dd><%= @produto.quantidade %></dd>

  <dt>Vecimento:</dt>
  <dd><%= @produto.vecimento %></dd>

  <dt>Preco compra:</dt>
  <dd><%= @produto.preco_compra %></dd>

  <dt>Preco venda:</dt>
  <dd><%= @produto.preco_venda %></dd>

</dl>